version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 2000:80
    environment:
      MYSQL_DATABASE: doctruyen
      MYSQL_ROOT_PASSWORD: 123456
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

app:
    container_name: app
    build: ./docker/src
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - 3306:80

volumes:
  db: